## Server Properties
server:
  port: 8080
  compression:
    enabled: true

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/twilio?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
    username:
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

## Hibernate Logging
logging:
  level:
    org.hibernate.SQL: DEBUG

sms-provider:
  type: twilio #[twilio,log] twilio for using twilio sent sms
  phone-number-default: 
  use-phone-number-default: true
  channel-type: sms #[sms, call, email, whatsapp, sna]
  twilio:
    account-sid:
    auth-token:
    message-service-sid:
    verify-service-sid:
